### ISSUE TITLE
had an odd issue concerning check(string $url)

### ISSUE THREAD

**Issue by vishtany** [hedii/uptime-checker#1]
receive a
`[19-Jun-2017 00:36:10 America/New_York] PHP Catchable fatal error:  Argument 1 passed to Hedii\UptimeChecker\UptimeChecker::check() must be an instance of Hedii\UptimeChecker\string, string given, called in /home/bitveuba/bitp.in/functions.php on line 22 and defined in /home/bitveuba/bitp.in/vendor/hedii/uptime-checker/src/UptimeChecker.php on line 142
` in error log at [BITP.in/](http://bitp.in)

the only I could resolve the error was to remove 'string' from line 142 in /home/bitveuba/bitp.in/vendor/hedii/uptime-checker/src/UptimeChecker.php

**Comment by hedii** [comment]
This package needs php >= 7.0

What is your php version?

**Comment by vishtany** [comment]
7.0

**Comment by hedii** [comment]
Can't reproduce.

Everything is tested with php 7.0 (https://github.com/hedii/uptime-checker/blob/master/.travis.yml https://github.com/hedii/uptime-checker/blob/master/tests/UptimeCheckerTest.php) and tests are passing (https://travis-ci.org/hedii/uptime-checker/builds/244395477).

You may have to double check your configuration and/or code.
